linting and bump PHP 8.4
dotkernel/dot-helpers pull request #29
Opened 2024-10-23 15:10 UTC by SergiuBota1

#28

2024-10-23 18:21 UTC, alexmerlin requested changes

2024-10-23 18:21 UTC, alexmerlin commented on README.md
> +![OSS Lifecycle](https://img.shields.io/osslifecycle.svg?file_url=https%3A%2F%2Fraw.githubusercontent.com%2Fdotkernel%2Fdot-helpers%2FHEAD%2FOSSMETADATA)
Revert this line. This package does not need to target a custom branch.

2024-10-23 18:21 UTC, alexmerlin commented on README.md
@arhimede should we also remove the wrapper badge and warning text from the wrapper packages?
If yes, @SergiuBota1 don't forget to remove them from `docs/book/v3/overview.md` as well.

2024-10-25 10:45 UTC, arhimede commented on README.md
We should remove the wrapper badge only from everywhere, including documentation, because is not functional anyway .
Wrapper text notice should stay, because  it is a wrapper anyway

2024-10-28 06:48 UTC, alexmerlin approved these changes

2024-10-28 10:28 UTC, merged